--- 
- 
  hosts: tmh
  name: Install PostgreSQL
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  
  tasks:
    - name: File repository configuration
      tags:
      - file_repo      
      command: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

    - name: Import repository signing key
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present
        
    - name: Install PostgreSQL
      tags:
      - postgresql
      apt:
        name: postgresql
        update_cache: yes
